server:
  port: 1145
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 101.201.173.110:8848
    gateway:
      routes:
        - id: followPart
          uri: lb://followPart
          predicates:
            - Path=/follow/**
        - id: messagePart
          uri: lb://messagePart
          predicates:
            - Path=/message/**
        - id: commentPart
          uri: lb://commentPart
          predicates:
            - Path=/comment/**,/commentUp/**
        - id: songPart
          uri: lb://songPart
          predicates:
            - Path=/song/**,/songList/**,/listSong/**,/recentSong/**
        - id: userPart
          uri: lb://userPart
          predicates:
            - Path=/admin/**,/user/**,/mail/**
        - id: extraPart
          uri: lb://extraPart
          predicates:
            - Path=/rank/**,/collect/**,/complaint/**
  main:
    web-application-type: reactive